<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/Images/SN_logo.png" width="300" alt="cognitiveclass.ai logo">
</center>

<h1>Extracting Stock Data Using a Web Scraping</h1>

Not all stock data is available via the API in this assignment; you will use web-scraping to obtain financial data. You will be quizzed on your results.  
You will extract and share historical data from a web page using the BeautifulSoup library.

In [ ]:
!pip install pandas
!pip install requests
!pip install bs4
!pip install html5lib
!pip install lxml
!pip install plotly

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
import warnings
# Ignore all warnings
warnings.filterwarnings("ignore", category=FutureWarning)

## Using Webscraping to Extract Stock Data Example

We will extract Netflix stock data from the provided URL.

In [ ]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/netflix_data_webpage.html"
data  = requests.get(url).text
print(data)

In [ ]:
soup = BeautifulSoup(data, 'html.parser')

In [ ]:
netflix_data = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close", "Volume"])

for row in soup.find("tbody").find_all('tr'):
    col = row.find_all("td")
    date = col[0].text
    Open = col[1].text
    high = col[2].text
    low = col[3].text
    close = col[4].text
    adj_close = col[5].text
    volume = col[6].text
    
    netflix_data = pd.concat([netflix_data, pd.DataFrame({"Date":[date], "Open":[Open], "High":[high], "Low":[low], "Close":[close], "Adj Close":[adj_close], "Volume":[volume]})], ignore_index=True)

In [ ]:
netflix_data.head()

## Extracting data using `pandas` library

In [ ]:
read_html_pandas_data = pd.read_html(url)

In [ ]:
from io import StringIO
read_html_pandas_data = pd.read_html(StringIO(str(soup)))

In [ ]:
netflix_dataframe = read_html_pandas_data[0]
netflix_dataframe.head()

# Exercise: use webscraping to extract stock data

Use the `requests` library to download the webpage containing Amazon stock data. Save the text of the response as a variable named `html_data`.

In [ ]:
url_amazon = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/amazon_data_webpage.html"
html_data = requests.get(url_amazon).text

Parse the html data using `beautiful_soup`.

In [ ]:
soup = BeautifulSoup(html_data, 'html.parser')

**Question 1:** What is the content of the title tag?

In [ ]:
# Question 1: Content of the title tag
title_content = soup.find('title').text
print(title_content)

Amazon.com, Inc. (AMZN) Stock Historical Prices & Data - Yahoo Finance

**Jawaban Question 1:** `Amazon.com, Inc. (AMZN) Stock Historical Prices & Data - Yahoo Finance`

Using BeautifulSoup, extract the table with historical share prices and store it into a data frame named `amazon_data`.

In [ ]:
amazon_data = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close", "Volume"])

for row in soup.find("tbody").find_all("tr"):
    col = row.find_all("td")
    date = col[0].text
    Open = col[1].text
    high = col[2].text
    low = col[3].text
    close = col[4].text
    adj_close = col[5].text
    volume = col[6].text
    
    amazon_data = pd.concat([amazon_data, pd.DataFrame({"Date":[date], "Open":[Open], "High":[high], "Low":[low], "Close":[close], "Adj Close":[adj_close], "Volume":[volume]})], ignore_index=True)

amazon_data.head()

           Date      Open      High       Low     Close Adj Close       Volume
0  Jan 31, 2021  3,206.20  3,267.97  3,175.10  3,206.22  3,206.22    4,697,700
1  Dec 31, 2020  3,186.75  3,350.65  3,168.01  3,256.93  3,256.93   83,721,800
2  Nov 30, 2020  3,163.53  3,463.49  3,077.49  3,168.04  3,168.04   75,710,600
3  Oct 31, 2020  3,200.00  3,552.25  2,871.00  3,036.15  3,036.15  121,964,900
4  Sep 30, 2020  3,148.00  3,552.25  2,871.00  3,148.73  3,148.73   92,688,600

**Question 2:** What are the names of the columns in the data frame?

In [ ]:
# Question 2: Column names
print(amazon_data.columns)

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

**Jawaban Question 2:** `Date, Open, High, Low, Close, Adj Close, Volume`

**Question 3:** What is the `Open` of the last row of the amazon_data data frame?

In [ ]:
# Question 3: Open of last row
print("Open value of the last row:", amazon_data['Open'].iloc[-1])
print("\nLast row:")
amazon_data.tail(1)

Open value of the last row: 1,870.00

Last row:

           Date      Open      High       Low     Close Adj Close      Volume
29  Aug 31, 2018  1,870.00  2,050.49  1,822.44  1,995.58  1,995.58  59,291,300

**Jawaban Question 3:** `1,870.00`

---

## Ringkasan Jawaban

| No | Pertanyaan | Jawaban |
|---|---|---|
| Q1 | Content of the title tag | `Amazon.com, Inc. (AMZN) Stock Historical Prices & Data - Yahoo Finance` |
| Q2 | Column names in the data frame | `Date, Open, High, Low, Close, Adj Close, Volume` |
| Q3 | Open of the last row | `1,870.00` |

<h2>About the Authors:</h2>

<a href="https://www.linkedin.com/in/joseph-s-50398b136/">Joseph Santarcangelo</a> has a PhD in Electrical Engineering.

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>